name: CI

on: 
  push:
    branches:
      - netcoreapp2.0
      - release/*
      - build

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402' # SDK Version to use.
    - name: restore package dependencies
      run: dotnet restore src/IdentityServer4.WsFederation/IdentityServer4.WsFederation.csproj
    - name: build package
      run: dotnet build --no-restore src/IdentityServer4.WsFederation/IdentityServer4.WsFederation.csproj
    - name: test package
      run: dotnet test --no-build --no-restore src/IdentityServer4.WsFederation/IdentityServer4.WsFederation.csproj
    - name: pack package
      run: >
        dotnet pack 
        --no-build 
        --no-restore 
        --output $GITHUB_WORKSPACE/dist 
        -p:PackageId=IdentityServer4.WsFederation 
        -p:PackageVersion=2.4.0
        src/IdentityServer4.WsFederation/IdentityServer4.WsFederation.csproj
    - name: Run a multi-line script
      run: |
        ls -al $GITHUB_WORKSPACE/dist
        echo test, and deploy your project.
