name: CI

on:
  push:
    tags:
      - '*'

env:
  PROJECT_FILE: src/IdentityServer4.WsFederation/IdentityServer4.WsFederation.csproj
  RELEASE_PACKAGE_ID: IdentityServer4.WsFederation
  RELEASE_VERSION: 2.4.0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.402' # SDK Version to use.
    - name: restore package dependencies
      run: dotnet restore ${{env.PROJECT_FILE}}
    - name: build package
      run: dotnet build --no-restore ${{env.PROJECT_FILE}}
    - name: test package
      run: dotnet test --no-build --no-restore ${{env.PROJECT_FILE}}
    - name: pack package
      run: >
        dotnet pack 
        --no-build 
        --no-restore 
        --output $GITHUB_WORKSPACE/dist 
        -p:PackageId=${{env.RELEASE_PACKAGE_ID}}
        -p:PackageVersion=${{env.RELEASE_VERSION}}
        ${{env.PROJECT_FILE}}
    - name: Upload a NuGet package
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{env.RELEASE_PACKAGE_ID}}-v${{env.RELEASE_VERSION}}
        # A file, directory or wildcard pattern that describes what to upload
        path: ./dist/*.nupkg
